/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { INFT, INFTInterface } from "../../../contracts/interfaces/INFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenUri",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INFT__factory {
  static readonly abi = _abi;
  static createInterface(): INFTInterface {
    return new Interface(_abi) as INFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INFT {
    return new Contract(address, _abi, runner) as unknown as INFT;
  }
}
